config/routes.rb
Transparency::Application.routes.draw do
  devise_for :users

  root "dashboard#show"

  resource :dashboard, :controller => :dashboard, :only => [:show, :create]
  resource :user, :controller => :user, :only => [:edit, :update]
  resources :projects, :only => [:show, :create]

  namespace :api do
    resources :foreign_projects
    resources :foreign_tasks
  end

  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :tasks

  validates :name, :presence => true
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user

  has_many :tasks, :dependent => :destroy

  validates :user_id, :presence => true
  validates :name, :presence => true

  def self.accessible_by(user)
    user.admin? ? self.all : self.where("user_id = ?", user.id)
  end

  def self.active_for_daterange(daterange)
    arel = self.joins(:tasks)
    arel = arel.where(:tasks => {:started_at => daterange.start_date..daterange.end_date})
    arel = arel.distinct
  end
end

app/models/project_analytic.rb
class ProjectAnalytic
  attr_accessor :project_windows

  def initialize(project_windows)
    @project_windows = project_windows
  end

  def total_hours
    project_windows.sum(&:total_hours).round(2)
  end
end

app/models/project_window.rb
class ProjectWindow
  attr_accessor :project, :daterange

  def initialize(project, daterange=nil)
    @project = project
    @daterange = daterange || Daterange.new(Date.today.beginning_of_month, Date.today.end_of_month)
  end

  def self.for_projects(projects, daterange=nil)
    projects.map {|project| self.new(project, daterange)}
  end

  def project_name
    self.project.name
  end

  def tasks
    @tasks ||= self.project.tasks.where(:started_at => @daterange.start_date .. @daterange.end_date).order(:started_at)
  end

  def total_hours
    self.tasks.to_a.sum(&:hours).round(2)
  end

  def total_days
    self.daterange.count
  end

  def hours_by_day
    @hours_by_day ||= self.daterange.map do |date|
      self.tasks_for_date(date).sum(&:hours).round(2)
    end
  end

  def tasks_by_date
    self.daterange.map { |date| self.tasks_for_date(date) }
  end

  def tasks_for_date(date)
    self.tasks.find_all {|t| 
      t.started_at.strftime("%Y%m%d") == date.strftime("%Y%m%d")
    }
  end

  def average_hours
    self.total_hours / self.tasks.size
  end
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :category

  validates :project_id, :presence => true
  validates :name, :presence => true
end

app/models/task_query.rb
class TaskQuery
  def range_of_months(projects)
    relation = Task.where(:project_id => projects.map(&:id))
    relation = relation.order(:started_at)
    relation.pluck(:started_at).map {|d| d.beginning_of_month.to_date}.uniq
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :recoverable, :rememberable, :trackable, 
         :validatable, :token_authenticatable

  has_many :projects
  has_many :tasks, :through => :projects

  before_create :ensure_authentication_token

  def admin?
    self.role == 'admin'
  end
end

app/controllers/api/foreign_projects_controller.rb
class Api::ForeignProjectsController < ApplicationController
  respond_to :json

  skip_before_filter :verify_authenticity_token

  before_filter :authenticate_user!
  before_filter :authorize_admin

  def create
    user = User.find_by_remote_id(params[:remote_client_id])
    project = user.projects.where(remote_id: params[:remote_project_id], name: params[:name]).first_or_initialize

    if project.new_record?
      if project.save
        render :json => project.to_json
      else
        render :json => {:error => "Unable to findor create project"}
      end
    else
      render :json => project.to_json
    end
  end

  private

  def authorize_admin
    unless current_user.admin?
      render :json => {:error => "unauthorized access"}
      return
    end
  end
end

app/controllers/api/foreign_tasks_controller.rb
class Api::ForeignTasksController < ApplicationController
  skip_before_filter :verify_authenticity_token

  before_filter :authenticate_user!
  before_filter :authorize_admin

  respond_to :json

  def create
    project = Project.find_by_remote_id(params[:remote_project_id])
    category = Category.where(:name => params[:category]).first_or_create
    task = project.tasks.where(:remote_id => params[:remote_task_id]).first_or_initialize

    if task.new_record?
      task.attributes = {
        :name => params[:name],
        :category => category,
        :hours => params[:hours],
        :started_at => params[:started_at],
      }

      if task.save
        render :json => task
      else
        render :json => {:error => "Unable to findor create project"}
      end
    else
      render :json => task
    end
  end

  private

  def authorize_admin
    unless current_user.admin?
      render :json => {:error => "unauthorized access"}
      return
    end
  end
end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authorize_admin

  def create
    user = User.find_by_remote_id(params[:remote_client_id])
    project = user.projects.find_or_initialize_by(remote_id: params[:remote_project_id], name: params[:name])

    if project.new_record?
      if project.save
        render :json => project.to_json
      else
        render :json => {:error => "Unable to findor create project"}
      end
    else
      render :json => project.to_json
    end
  end

  private

  def authorize_admin
    unless current_user.admin?
      render :json => {:error => "unauthorized access"}
      return
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_filter :authenticate_user!

  def show
    @month = Date.today.beginning_of_month
    @daterange = Daterange.new(@month, @month.end_of_month)

    projects = Project.accessible_by(current_user).active_for_daterange(@daterange)
    prepare_dashboard(projects, @daterange)
  end

  def create
    @month = Date.parse(params[:month]).beginning_of_month

    @daterange = Daterange.new(@month, @month.end_of_month)

    projects = Project.accessible_by(current_user).active_for_daterange(@daterange)
    prepare_dashboard(projects, @daterange)

    render :show
  end

  private

  def prepare_dashboard(projects, daterange)
    @project_windows = ProjectWindow.for_projects(projects, daterange)
    @project_analytic = ProjectAnalytic.new(@project_windows)

    @months = TaskQuery.new.range_of_months(projects)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!

  def show
    @month = params[:month] ? Date.parse(params[:month]) : Date.today
    prepare_project_page
  end

  def create
    @month = Date.parse(params[:month])
    prepare_project_page

    render :show
  end

  private

  def prepare_project_page
    @daterange = Daterange.new(@month.beginning_of_month, @month.end_of_month)

    @project = Project.accessible_by(current_user).active_for_daterange(@daterange).find(params[:id] || params[:project_id])
    @project_window = ProjectWindow.new(@project, @daterange)
    @months = TaskQuery.new.range_of_months([@project])
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :authenticate_user!

  def edit
    @user = current_user
  end

  def update
    @user = User.find(current_user.id)

    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
    end

    if @user.update_attributes(user_params)
      sign_in @user, :bypass => true
      redirect_to root_path, :notice => "Your account was successfully updated"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/dashboard/show.html.erb
<%= javascript_tag do %>
  var percentages_data = [
    <% @project_windows.each do |project_window| %>
      { 
        label: "<%= project_window.project_name %>",
        value: <%= project_window.total_hours %> 
      },
    <% end %>
  ];
  
  var hour_data = new Array;
  var ykeys = new Array;

  <% @project_windows.each do |project_window| %>
    ykeys.push("<%=project_window.project_name%>");

    <% project_window.hours_by_day.each_with_index do |hour, i| %>
      var date = "<%= project_window.daterange[i].strftime('%Y-%m-%d') %>";
      hour_data[<%=i%>] || (hour_data[<%=i%>] = {});
      hour_data[<%=i%>]['y'] = date;
      hour_data[<%=i%>]["<%=project_window.project_name%>"] = <%=hour%>;
    <% end %>
  <% end %>
<% end %>

<div class="row page-header">
  <h2 class="col-md-12">Project Hours by Day</h2>
  <%= form_tag dashboard_path, :class => 'col-lg-4' do %>
    <%= select_tag "month", options_for_select(@months.map {|m| [m.strftime("%B %Y"), m]}, @month), :class => "form-control", :id => "month-selector" %>
  <% end %>
</div>

<div class='row top-buffer'>
  <div id="project-percentages" class="col-md-4" style="height: 300px"></div>
  <div id="daily_hours" class="col-md-8" style="height: 300px"></div>
</div>

<div class='row top-double_buffer'>
<table id='project-breakdown' class='table table-striped table-condensed'>
<thead>
  <tr>
    <th>Project</th>
    <% @daterange.each do |date| %>
      <th><%= date.strftime("%d") %></th>
    <% end %>
    <th>Total</th>
  </tr>
</thead>
<tbody>
  <% @project_windows.each do |project_window| %>
    <tr>
      <td><%= link_to project_window.project_name, project_path(project_window.project, {:month => @month.to_s}) %></td>
      <% project_window.hours_by_day.each do |hours| %>
        <td class='numeric'><%= hours %></td>
      <% end %> 
      <td class='numeric'><%= project_window.total_hours %></td>
    </tr>
  <% end %>
  <tr>
    <td colspan="<%= @daterange.count + 2 %>" style="text-align: right">
      <strong>Total Hours:</strong> <%= @project_analytic.total_hours %>
    </td>
  </tr>
</tbody>
</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Transparency</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-default">
    <div class='container'>
      <div class="navbar-header">
        <%= image_tag "redcoyote-logo-sm.png" %>
      </div>
      <% if user_signed_in? %>
        <div class="navbar-inner">
          <% unless current_page?(root_path) %>
            <ul class="nav navbar-nav">
              <li><%= link_to "Home", root_path %></li>
            </ul>
          <% end %>
          <ul class="nav navbar-nav navbar-right">
            <div class="btn-group navbar-form">
              <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                <span class="glyphicon glyphicon-cog"></span>
                <span class='caret'></span>
              </button>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Account", edit_user_path %></li>
                <li class='divider'></li>
                <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
              </ul>

            </div>
          </ul>
        </div>
      <% end %>
    </div>
  </div>

  <div class='container'>
    <% if notice %>
      <div class="alert alert-success"><%= notice %></div>
    <% elsif alert %>
      <div class="alert alert-danger"><%= alert %></div>
    <% end %>

    <%= yield %>

  </div>
</body>
</html>

app/views/projects/show.html.erb
<%= javascript_tag do %>
  var project_data = new Array;
  var ykeys = new Array;

  ykeys.push("<%=@project_window.project_name%>");

  <% @project_window.hours_by_day.each_with_index do |hour, i| %>
    var date = "<%= @project_window.daterange[i].strftime('%Y-%m-%d') %>";
    project_data[<%=i%>] || (project_data[<%=i%>] = {});
    project_data[<%=i%>]['y'] = date;
    project_data[<%=i%>]["<%=@project_window.project_name%>"] = <%=hour%>;
  <% end %>
<% end %>

<div class="row page-header">
  <h2 class="col-md-12"><%= @project.name %> Details</h2>
  <%= form_tag projects_path, :class => 'col-lg-4' do %>
    <%= hidden_field_tag "project_id", @project.id %>
    <%= select_tag "month", options_for_select(@months.map {|m| [m.strftime("%B %Y"), m.to_s(:db)]}, @month.to_s(:db)), :class => "form-control", :id => "month-selector" %>
  <% end %>
</div>

<div class='row top-buffer'>
  <div id="project-month" class="col-md-12" style="height: 300px"></div>
  <!--
  <div id="project-year" class="col-md-12" style="height: 100px"></div>
  -->
</div>

<div class='row top-double_buffer'>
<table id='task-breakdown' class='table table-striped table-condensed'>
  <thead>
  <tr>
    <th>Project</th>
    <% @daterange.each do |date| %>
      <th><%= date.strftime("%d") %></th>
    <% end %>
  </tr>
  </thead>

  <tbody>
  <% @project_window.tasks_by_date.each_with_index do |tasks,i| %>
    <% tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <% @daterange.count.times do |j| %>
          <% if j == i %>
            <td class='numeric'><%= task.hours %></td>
            <%else%>
            <td class='numeric'></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>
</div>

app/views/user/edit.html.erb
<div class="row">
  <div class="col-md-5">
    <%= simple_form_for @user, :html => {:class => "form-vertical"}, :defaults => {:wrapper_html => {:class => "form-group"}, :input_html => {:class => "form-control"}} do |f| %>
      <div class="form-inputs">
        <%= f.input :email, :disabled => true %>
        <%= f.input :password %>
        <%= f.input :password_confirmation %>
      </div>

      <div class="form-actions">
        <%= f.button :submit, "Update", :class => "btn btn-primary btn-block" %>
      </div>
    <% end %>
  </div>
</div>